development:
  adapter: postgresql
  encoding: unicode
  database: lead_management
  host: localhost
  pool: 5
  username: postgres
  password: 123
production:
  adapter: postgresql
  encoding: unicode
  database: lead_management_test
  host: localhost
  pool: 5
  username: postgres
  password: 123
